### ISSUE TITLE
starting and ending point in the map

### ISSUE THREAD

**Issue by LorenzoFerro15** [softeng2team15/se2022-15-HikeTracker#11]
As a Hiker I really like the interface and the fact that I can see the map of the hike in the card, but I would like to have a way to recognize the starting and the ending point in the map. they have a marker with a different colour but I think a legend is needed to clarify the kind of point

**Comment by moyne** [comment]
Thanks for the feedback, now we changed the whole icons and added a glossary for more comprehension to the users
